device: {
    SM1 {
        grid-rows: 3
        ALU1
        ALU2
        ALU3
        ALU4
        ALU5
        ALU6
    }
    SM2 {
        grid-rows: 3
        ALU1
        ALU2
        ALU3
        ALU4
        ALU5
        ALU6
    }
    SM3 { 
        grid-rows: 3
        ALU1
        ALU2
        ALU3
        ALU4
        ALU5
        ALU6
    }
    SM4 { 
        grid-rows: 3
        ALU1
        ALU2
        ALU3
        ALU4
        ALU5
        ALU6
    }

    mem {
        height: 200
    }
}
